theme: jekyll-theme-minimal
title: Data Structures and Algorithms Using Java - Training
description: Training page of Data Structures and Algorithms Using Java
show_downloads: false
author: 'Sathish G'
subtitle: 'RVS College of Arts and Science'
github:
  is_project_page: false
